backend:
  build: ./backend
  command: bash start.sh
  volumes:
    - ./backend:/app:rw
    - ~/.bash_history:/root/.bash_history
    - .build/.bundle-cache-dir/app:/usr/local/bundle/
  ports:
    - "3000"
  links:
    - postgres
    - redis
  environment:
    - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    - REDIS_URL=redis://redis:6379/
    - EDITOR=vim
    - HTTP_HOST=http://localhost:3000

redis:
  image: redis
  ports:
    - "6379"

postgres:
  image: postgres:9.6.8
  ports:
    - '5432'
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=1234
  volumes:
    - ./.db_pg:/var/lib/postgresql/data

frontend:
  build: ./frontend
  entrypoint: []
  command: ng serve --host 0.0.0.0
  volumes:
    - ./frontend:/myapp
  ports:
    - "4200"

nginx:
  build: ./nginx
  command: nginx -g 'daemon off;'
  ports:
    - "3000:80"
  environment:
    - NGINX_HOST=127.0.0.1
    - NGINX_PORT=80
  links:
    - backend
    - frontend
  volumes:
    -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
